// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpHdD7V6QCSwO-8_pAGeXJqo_pC6RO2xM',
    appId: '1:208936940223:web:43193d33cbd2d26fe8cc0a',
    messagingSenderId: '208936940223',
    projectId: 'clone-7b308',
    authDomain: 'clone-7b308.firebaseapp.com',
    storageBucket: 'clone-7b308.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5NURhMlxQLvKKFeDgqgEMlvLflWXcH9A',
    appId: '1:208936940223:android:96d1951f9eb002d8e8cc0a',
    messagingSenderId: '208936940223',
    projectId: 'clone-7b308',
    storageBucket: 'clone-7b308.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt7QPrNMOOsGvpBhxz-jAb9d_BxBTbmgw',
    appId: '1:208936940223:ios:01483188e78eac8fe8cc0a',
    messagingSenderId: '208936940223',
    projectId: 'clone-7b308',
    storageBucket: 'clone-7b308.appspot.com',
    iosBundleId: 'com.example.youtubeClone',
  );
}
