// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOUf0Qo2oS2QsijopW65AlHkmnuXSXyME',
    appId: '1:449640566695:web:b232e5aaa388e311da7082',
    messagingSenderId: '449640566695',
    projectId: 'clone-65e4d',
    authDomain: 'clone-65e4d.firebaseapp.com',
    storageBucket: 'clone-65e4d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAND-EzFv8V3T0dEvbG9SFcfeKPIwrdyoc',
    appId: '1:449640566695:android:16cd79503a1fe104da7082',
    messagingSenderId: '449640566695',
    projectId: 'clone-65e4d',
    storageBucket: 'clone-65e4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUJkDOAqR_AXHb-PEfW-mFkojhHyyaPsM',
    appId: '1:449640566695:ios:6bc2be062600af76da7082',
    messagingSenderId: '449640566695',
    projectId: 'clone-65e4d',
    storageBucket: 'clone-65e4d.appspot.com',
    iosBundleId: 'com.example.youtubeClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUJkDOAqR_AXHb-PEfW-mFkojhHyyaPsM',
    appId: '1:449640566695:ios:d408a9ffbfb3764cda7082',
    messagingSenderId: '449640566695',
    projectId: 'clone-65e4d',
    storageBucket: 'clone-65e4d.appspot.com',
    iosBundleId: 'com.example.youtubeClone.RunnerTests',
  );
}
